language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
sudo: false
install:
  - npm install --fallback-to-build=false
  - npm install tilestrata
script:
  - make test && (make test-ci-coverage || true)
